### ISSUE TITLE
所以启动键是哪个呢 我都全按了一遍也没作用

### ISSUE THREAD

**Issue by BLUE-POISON096** [nano71/CSGOLuaScript#1]
![Uploading 屏幕截图 2024-10-13 190944.png…]()

**Comment by BLUE-POISON096** [comment]
![屏幕截图 2024-10-13 190944](https://github.com/user-attachments/assets/8f947cb6-ad9a-4e01-9093-8a67982299ce)

**Comment by nano71** [comment]
lua里你设置哪个就是按哪个启用
